rm */WAVECAR
rm */CHG
rm */CHGCAR
rm */vasprun.xml
rm */*/WAVECAR
rm */*/CHG
rm */*/CHGCAR
rm */*/vasprun.xml
rm */*/*/WAVECAR
rm */*/*/CHG
rm */*/*/CHGCAR
rm */*/*/vasprun.xml

rm */*/*/*/WAVECAR
rm */*/*/*/CHG
rm */*/*/*/CHGCAR
rm */*/*/*/vasprun.xml
rm */*/*/*/*/WAVECAR
rm */*/*/*/*/CHG
rm */*/*/*/*/CHGCAR
rm */*/*/*/*/vasprun.xml
rm */*/*/*/*/*/*/WAVECAR
rm */*/*/*/*/*/*/CHG
rm */*/*/*/*/*/*/CHGCAR
rm */*/*/*/*/*/*/vasprun.xml
rm */*/*/*/*/*/*/WAVECAR
rm */*/*/*/*/*/CHG
rm */*/*/*/*/*/CHGCAR
rm */*/*/*/*/*/vasprun.xml
